vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: false  # Usar nombres DNS en lugar de IPs
    hostname: vets-service  # Nombre del servicio en Kubernetes
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8083
eureka:
  instance:
    preferIpAddress: false
    hostname: vets-service  # Nombre del servicio en Kubernetes
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
